# Generated by Django 3.2.5 on 2022-02-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='game',
            name='developer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(max_length=100),
        ),
    ]
