# Generated by Django 3.2.5 on 2022-02-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220207_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
