# Generated by Django 3.2.5 on 2022-02-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220207_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='event_name',
        ),
        migrations.AddField(
            model_name='game',
            name='game_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
